image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

variables:
  CONTAINER_TEST_IMAGE: r1l-gitlab:4567/sages/openessence:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: r1l-gitlab:4567/sages/openessence:latest
  DOCKER_DRIVER: overlay

before_script: 
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  tags:
    - shell
  script:
    - docker build --pull -f Dockerfile.prod -t $CONTAINER_TEST_IMAGE . --build-arg COMMIT_HASH="$(git rev-parse --short HEAD)" --build-arg DEPLOY_DATE="$(date +%F)"
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  tags:
    - shell
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  when: manual
  only:
    - master